image: node:18

stages:
  - security
  - plan-infrastructure
  - test
  - deploy

# --- Security Checks (IaC) ---
# --- Security Checks (IaC) ---
secret_detection:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --source . --no-git
  allow_failure: true

dependency_scan:
  stage: security
  script:
    - npm audit --audit-level=high
  allow_failure: true

scan_infrastructure:
  stage: security
  image:
    name: aquasec/tfsec:v1.28.1
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - caso-c-terraform-s3/**/*
  script:
    - tfsec caso-c-terraform-s3

cache:
  paths:
    - node_modules/

# --- Global Checks ---
lint:
  stage: test
  script:
    - npm ci
    - npm run lint
  rules:
    - changes:
        - "**/*.{js,css,html,md}"
        - package.json
        - .eslintrc.js
        - .prettierrc

# --- Caso B: Legacy S3 Sync ---
deploy_case_b:
  stage: deploy
  image:
    name: public.ecr.aws/aws-cli/aws-cli:latest
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - caso-b-gitlab-s3/**/*
  script:
    - echo "Deploying Case B to S3..."
    - |
      if [ -z "$S3_BUCKET" ]; then
        echo "ERROR: La variable S3_BUCKET no está definida en GitLab CI/CD Variables."
        exit 1
      fi
    - aws s3 sync caso-b-gitlab-s3/ "s3://$S3_BUCKET/" --delete --exclude "*.md"
  environment:
    name: production/case-b

# --- Caso C: Terraform (Infraestructura y App) ---
plan_case_c:
  stage: plan-infrastructure
  image:
    name: hashicorp/terraform:1.14.3
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - caso-c-terraform-s3/**/*
  script:
    - cd caso-c-terraform-s3
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - caso-c-terraform-s3/tfplan
    expire_in: 1 hour

deploy_case_c:
  stage: deploy
  image:
    name: hashicorp/terraform:1.14.3
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - caso-c-terraform-s3/**/*
  needs:
    - plan_case_c
  script:
    - cd caso-c-terraform-s3
    - terraform init
    - terraform apply -auto-approve tfplan
  environment:
    name: production/case-c







pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html manifest.json sw.js *.md public/
    - cp -r assets docs wiki apps caso-* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
